### ISSUE TITLE
Taskflow and jaro_winkler headers are included in wheels and get installed in /usr/include

### ISSUE THREAD

**Issue by pekkarr** [maxbachmann/rapidfuzz#201] opened 2022-03-13 09:49 UTC
The Taskflow and jaro_winkler headers are installed into `/usr/include` when installing `rapidfuzz` system-wide on Linux. Because these are only used during compilation they should not be included in built wheels. Also some cmake files from Taskflow are installed under `/usr/lib/cmake/Taskflow`.

The jaro_winkler headers are installed twice: first directly under `/usr/include` and then under `/usr/include/jaro_winkler`.

**Comment by maxbachmann** [comment] 2022-03-13 14:08
Thanks for bringing this up:
1) The jaro_winkler headers are installed twice: first directly under /usr/include and then under /usr/include/jaro_winkler.
This appears to be a bug in the cmake config, which I fixed for https://github.com/maxbachmann/rapidfuzz-cpp, but forgot to fix in https://github.com/maxbachmann/jarowinkler-cpp
2) The jaro_winkler headers should not be installed when including as subproject similar to rapidfuzz-cpp. Fixed this in https://github.com/maxbachmann/jarowinkler-cpp
3) I do now prevent taskflow from installing

Fixed in https://github.com/maxbachmann/RapidFuzz/commit/23007633311e0416673c935b31b6890c88dd8f33

**Closed as completed by maxbachmann** 2022-03-13 14:08 UTC
Labels: bug

**Comment by pekkarr** [comment] 2022-04-15 11:29
This bug was reintroduced for jaro_winkler in c950f833d0589938ccf2884b9acb4a4f4e0ada91 that reverts `jarowinkler-cpp` submodule to the state before the fix.

**Comment by maxbachmann** [comment] 2022-04-15 15:40
Thanks for reporting. Reverting the submodule was definitely not intended 🤦

**Comment by maxbachmann** [comment] 2022-04-18 21:29
I fixed this regression again in v2.0.10: https://github.com/maxbachmann/RapidFuzz/releases/tag/v2.0.10
